### ISSUE TITLE
Adding animations to the header

### ISSUE THREAD

**Issue by rudranshg** [evilseye/Zoop-Hacktoberfest#49]
The headline looks very plain and simple. It can be enhanced with a background gradient animation as shown in screenshots below. I can work on it.

![2021-10-15 (3)](https://user-images.githubusercontent.com/82700547/137396411-629ca9f0-52e6-4ee1-a166-1edc63ae1e3e.png)
![2021-10-15 (4)](https://user-images.githubusercontent.com/82700547/137396408-06b1ea98-f1fb-4afe-9723-9d70c8e74a5b.png)

**Comment by evilseye** [comment]
Hye @rudranshg This looks great! I have assigned the issue to you. 
Thank you for contributing 😀

**Comment by AnshuPathak-88825** [comment]
assign me this issue

**Comment by pushpanjali-10** [comment]
can I work on this?
