### ISSUE TITLE
Contribute to Zoop

### ISSUE THREAD

**Issue by evilseye** [evilseye/Zoop-Hacktoberfest#8]
Add yourname.md in the Contributors folder.

**Comment by nemynigam** [comment]
Assign Me

**Comment by ananya224** [comment]
I am interested too ! Please assign

**Comment by PreetiBaskey** [comment]
hey @evilseye , i want to contribute to this issue , kindly assign me this issue .
Thank You.

**Comment by PreetiBaskey** [comment]
hey @harshit-sharma-gits , why you remove the label, may i know the reason.

**Comment by hasnainabeel** [comment]
Hey! @evilseye can you please assign me?
