### ISSUE TITLE
Improving color design

### ISSUE THREAD

**Issue by khushi818** [evilseye/Zoop-Hacktoberfest#80]
Hello , I think color looks too simple.
I can add some simple shades on background or cards. 
Color will  be the same but with slight enhancement.

**Comment by itsPrajapat** [comment]
Could you please assign this issue to me.

**Comment by Manishgupta200** [comment]
@khushi818 could you please assign it to me. I'm interesting to work on it

**Comment by evilseye** [comment]
That would be great @karmaAyshushi ! Thank you for contributing to Zoop.
