### ISSUE TITLE
NavBar for lower resolution 

### ISSUE THREAD

**Issue by Thisisakr47** [evilseye/Zoop-Hacktoberfest#89]
@evilseye 
**Issue** - The current Navbar for lower resolution (less than 991px) is not aligned properly making it less appealing. _I would like to fix this issue if you assign me_. 
<br>
Below are the snapshots of this issue at different width.
<br>
Current navbar at 400px width: - 
![before 400px](https://user-images.githubusercontent.com/74677018/137731872-6f3f953c-a718-489a-8626-e8dd5d66be04.png)
<br>
Fixed navbar at 400px width: -
![after 400px](https://user-images.githubusercontent.com/74677018/137732048-1fda43bd-0982-4275-a8e8-495ae5e6cd6f.png)
<br>
Current navbar at 800px width : -
![before 800px](https://user-images.githubusercontent.com/74677018/137731522-6017f7ae-2c08-46fa-9020-ad8769e83195.png)
<br>
Fixed navbar at 800px width : -
![after 800px](https://user-images.githubusercontent.com/74677018/137731659-ea3f4e0f-2da9-453e-9757-96bc8d1bff8d.png)

**Comment by evilseye** [comment]
This would be great @Thisisakr47 . I have assigned the issue to you.

**Comment by Manishgupta200** [comment]
I'll try to fix it. Please assign it to me
